name: Build and Deploy

on:
  push:
    branches: [ main, dev ]

env:
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
  VITE_PUBLIC_HOSTNAME: ${{ secrets.PUBLIC_HOSTNAME }}
  WORKER_NAME: ${{ github.event.repository.name }}

jobs:
  deploy-workers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deploy cloudflare workers
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run publish